import js from '@eslint/js';
import tseslint from '@typescript-eslint/eslint-plugin';
import tsparser from '@typescript-eslint/parser';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';

export default [
  js.configs.recommended,
  {
    files: ['**/*.{js,jsx,ts,tsx}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parser: tsparser,
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        window: 'readonly',
        Window: 'readonly',
        document: 'readonly',
        Document: 'readonly',
        navigator: 'readonly',
        Navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        React: 'readonly',
        Blob: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        fetch: 'readonly',
        confirm: 'readonly',
        alert: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        clearTimeout: 'readonly',
        MessageEvent: 'readonly',
        IntersectionObserver: 'readonly',
        IntersectionObserverInit: 'readonly',
        IntersectionObserverEntry: 'readonly',
        IntersectionObserverCallback: 'readonly',
        File: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLTextAreaElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLScriptElement: 'readonly',
        HTMLElement: 'readonly',
        Element: 'readonly',
        MediaRecorder: 'readonly',
        ResizeObserver: 'readonly',
        ResizeObserverCallback: 'readonly',
        MutationObserver: 'readonly',
        MutationCallback: 'readonly',
        MutationObserverInit: 'readonly',
        MutationRecord: 'readonly',
        NodeJS: 'readonly',
        DOMParser: 'readonly',
        FormData: 'readonly',
        CustomEvent: 'readonly',
        KeyboardEvent: 'readonly',
        MouseEvent: 'readonly',
        Node: 'readonly',
        TextEncoder: 'readonly',
        crypto: 'readonly',
        global: 'readonly',
        cancelAnimationFrame: 'readonly',
        requestAnimationFrame: 'readonly',
        AudioContext: 'readonly',
        Event: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        EventSource: 'readonly',
        EventListener: 'readonly',
        caches: 'readonly',
        IDBDatabase: 'readonly',
        indexedDB: 'readonly',
        IDBOpenDBRequest: 'readonly',
        Location: 'readonly',
        HTMLFormElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        ProgressEvent: 'readonly',
        FileReader: 'readonly',
        Notification: 'readonly',
        NotificationPermission: 'readonly',
        NotificationOptions: 'readonly',
        // Service Worker globals
        self: 'readonly',
        Response: 'readonly',
        clients: 'readonly',
        Cache: 'readonly',
        CacheStorage: 'readonly',
        ExtendableEvent: 'readonly',
        FetchEvent: 'readonly',
        ServiceWorkerRegistration: 'readonly',
        ServiceWorkerGlobalScope: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
      react,
      'react-hooks': reactHooks,
    },
    rules: {
      '@typescript-eslint/no-unused-vars': ['warn', { 
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        ignoreRestSiblings: true 
      }],
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-non-null-assertion': 'warn',
      '@typescript-eslint/ban-ts-comment': ['warn', { 'ts-expect-error': 'allow-with-description', 'ts-ignore': 'allow-with-description', 'ts-nocheck': 'allow-with-description' }],
      '@typescript-eslint/no-empty-function': 'off',
      '@typescript-eslint/no-var-requires': 'error',
      'preserve-caught-error': 'error',
      'no-throw-literal': 'error',
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      'react/display-name': 'off',
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'error',
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'no-debugger': 'error',
      'no-alert': 'warn',
      'no-prototype-builtins': 'warn',
      'no-empty': 'warn',
      'no-constant-condition': 'warn',
      'no-fallthrough': 'warn',
      'no-case-declarations': 'warn',
      'no-undef': 'error',
      'no-redeclare': 'error',
      'no-unused-vars': 'off',
      'no-sequences': 'warn',
      'no-return-await': 'warn',
      'no-async-promise-executor': 'error',
      'no-promise-executor-return': 'error',
      'prefer-const': 'error',
      'eqeqeq': 'error',
      'curly': 'error',
      'no-control-regex': 'warn',
      'no-useless-assignment': 'warn',
      'no-useless-catch': 'warn',
      'no-useless-escape': 'warn',
      'no-unused-eslint-disable-comments': 'off',
      'no-throw-literal': 'off',
      '@typescript-eslint/no-empty-function': 'warn',
      'react/display-name': 'off',
      'no-unused-vars': 'off',
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
  },
  {
    ignores: [
      // Dependencies
      'node_modules/**',
      'dist/**',
      'build/**',
      '.next/**',
      'out/**',
      // Environment files
      '.env',
      '.env.local',
      '.env.development.local',
      '.env.test.local',
      '.env.production.local',
      // Git
      '.git/**',
      '.github/**',
      // IDE
      '.vscode/**',
      '.idea/**',
      // OS
      '.DS_Store',
      // Documentation
      'docs/**',
      '*.md',
      // Tests
      'coverage/**',
      'test-results/**',
      '*.test.ts',
      '*.test.tsx',
      '*.spec.ts',
      '*.spec.tsx',
      // Config files
      '*.config.js',
      '*.config.ts',
      '.eslintrc.js',
      '.prettierrc',
      'eslint.config.js',
      // External tools and testing
      'postman/**',
      'scripts/**',
      'tools/**',
      // Deployment and license files
      'patches/**',
      'license-files/**',
      'deploy/**',
      // Diagnostic scripts
      'check_tables.js',
    ],
  },
];
