$kind: http-request
name: Delete Task
method: POST
url: '{{baseUrl}}/api/trpc/tasks.delete'
order: 5000
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {"json":{"id":1}}
