$kind: http-request
name: Get Task Attachments
method: GET
url: '{{baseUrl}}/api/trpc/tasks.getAttachments'
order: 13000
queryParams:
  - key: input
    value: '%7B%22json%22%3A%7B%22taskId%22%3A1%7D%7D'
