export const ROLE_BASE_KEYS = [
  'admin',
  'manager',
  'staff',
  'team_leader',
  'viewer',
  'user',
] as const;
export type RoleBaseKey = (typeof ROLE_BASE_KEYS)[number];

export const ROLE_PERMISSIONS = [
  'dashboard.view',
  'dashboard.customize',
  'users.view',
  'users.create',
  'users.update',
  'users.deactivate',
  'users.delete',
  'users.assign_role',
  'users.manage',
  'roles.manage',
  'roles.view',
  'content.view',
  'content.create',
  'content.update',
  'content.delete',
  'content.restore',
  'content.review',
  'content.manage',
  'content.publish',
  'media.view',
  'media.upload',
  'media.organize',
  'media.download',
  'media.rename',
  'media.delete',
  'media.manage',
  'appointments.view',
  'appointments.create',
  'appointments.update',
  'appointments.cancel',
  'appointments.delete',
  'appointments.assign',
  'appointments.export',
  'appointments.manage',
  'leads.view',
  'leads.create',
  'leads.update',
  'leads.assign',
  'leads.export',
  'leads.delete',
  'leads.manage',
  'communications.view',
  'communications.reply',
  'communications.assign',
  'communications.broadcast',
  'communications.templates.manage',
  'communications.archive',
  'communications.delete',
  'communications.manage',
  'campaigns.view',
  'campaigns.create',
  'campaigns.update',
  'campaigns.delete',
  'campaigns.publish',
  'campaigns.archive',
  'campaigns.export',
  'campaigns.manage',
  'reports.view',
  'reports.export',
  'tasks.view',
  'tasks.create',
  'tasks.update',
  'tasks.assign',
  'tasks.complete',
  'tasks.delete',
  'tasks.manage',
  'notifications.view',
  'notifications.send',
  'notifications.settings.manage',
  'notifications.manage',
  'settings.view',
  'settings.manage',
  'integrations.view',
  'integrations.connect',
  'integrations.disconnect',
  'integrations.credentials.manage',
  'integrations.manage',
  'privacy.view',
  'privacy.manage',
  'privacy.export',
  'operations.view',
  'operations.import',
  'operations.export',
  'operations.backup',
  'operations.restore',
  'operations.manage',
  'audit.view',
  'audit.export',
] as const;

export type RolePermission = (typeof ROLE_PERMISSIONS)[number];

export const ROLE_PERMISSION_GROUPS = [
  {
    key: 'dashboard',
    label: 'لوحة التحكم والتقارير',
    permissions: ['dashboard.view', 'dashboard.customize', 'reports.view', 'reports.export'],
  },
  {
    key: 'users',
    label: 'المستخدمون والأدوار',
    permissions: [
      'users.view',
      'users.create',
      'users.update',
      'users.deactivate',
      'users.delete',
      'users.assign_role',
      'users.manage',
      'roles.view',
      'roles.manage',
    ],
  },
  {
    key: 'content',
    label: 'المحتوى والنشر',
    permissions: [
      'content.view',
      'content.create',
      'content.update',
      'content.delete',
      'content.restore',
      'content.review',
      'content.manage',
      'content.publish',
    ],
  },
  {
    key: 'media',
    label: 'الوسائط',
    permissions: [
      'media.view',
      'media.upload',
      'media.organize',
      'media.download',
      'media.rename',
      'media.delete',
      'media.manage',
    ],
  },
  {
    key: 'appointments',
    label: 'المواعيد والتسجيلات',
    permissions: [
      'appointments.view',
      'appointments.create',
      'appointments.update',
      'appointments.cancel',
      'appointments.delete',
      'appointments.assign',
      'appointments.export',
      'appointments.manage',
    ],
  },
  {
    key: 'leads',
    label: 'العملاء المحتملون',
    permissions: [
      'leads.view',
      'leads.create',
      'leads.update',
      'leads.assign',
      'leads.export',
      'leads.delete',
      'leads.manage',
    ],
  },
  {
    key: 'communications',
    label: 'التواصل والصندوق الموحد',
    permissions: [
      'communications.view',
      'communications.reply',
      'communications.assign',
      'communications.broadcast',
      'communications.templates.manage',
      'communications.archive',
      'communications.delete',
      'communications.manage',
    ],
  },
  {
    key: 'campaigns',
    label: 'الحملات التسويقية',
    permissions: [
      'campaigns.view',
      'campaigns.create',
      'campaigns.update',
      'campaigns.delete',
      'campaigns.publish',
      'campaigns.archive',
      'campaigns.export',
      'campaigns.manage',
    ],
  },
  {
    key: 'tasks',
    label: 'المهام والمتابعة',
    permissions: [
      'tasks.view',
      'tasks.create',
      'tasks.update',
      'tasks.assign',
      'tasks.complete',
      'tasks.delete',
      'tasks.manage',
    ],
  },
  {
    key: 'governance',
    label: 'الحوكمة والإعدادات',
    permissions: [
      'notifications.view',
      'notifications.send',
      'notifications.settings.manage',
      'notifications.manage',
      'settings.view',
      'settings.manage',
      'integrations.view',
      'integrations.connect',
      'integrations.disconnect',
      'integrations.credentials.manage',
      'integrations.manage',
      'privacy.view',
      'privacy.manage',
      'privacy.export',
      'operations.view',
      'operations.import',
      'operations.export',
      'operations.backup',
      'operations.restore',
      'operations.manage',
      'audit.view',
      'audit.export',
    ],
  },
] as const satisfies ReadonlyArray<{
  key: string;
  label: string;
  permissions: readonly RolePermission[];
}>;

export const ROLE_PERMISSION_LABELS: Record<RolePermission, string> = {
  'dashboard.view': 'عرض لوحة التحكم',
  'dashboard.customize': 'تخصيص لوحة التحكم',
  'users.view': 'عرض المستخدمين',
  'users.create': 'إضافة مستخدمين',
  'users.update': 'تعديل المستخدمين',
  'users.deactivate': 'تعطيل المستخدمين',
  'users.delete': 'حذف المستخدمين',
  'users.assign_role': 'تعيين أدوار المستخدمين',
  'users.manage': 'إدارة المستخدمين بالكامل',
  'roles.manage': 'إدارة الأدوار والصلاحيات',
  'roles.view': 'عرض الأدوار والصلاحيات',
  'content.view': 'عرض المحتوى',
  'content.create': 'إنشاء المحتوى',
  'content.update': 'تعديل المحتوى',
  'content.delete': 'حذف المحتوى',
  'content.restore': 'استعادة المحتوى',
  'content.review': 'مراجعة المحتوى',
  'content.manage': 'إدارة المحتوى بالكامل',
  'content.publish': 'نشر المحتوى',
  'media.view': 'عرض مكتبة الوسائط',
  'media.upload': 'رفع الوسائط',
  'media.organize': 'تنظيم المجلدات والوسائط',
  'media.download': 'تنزيل الوسائط',
  'media.rename': 'إعادة تسمية الوسائط',
  'media.delete': 'حذف الوسائط',
  'media.manage': 'إدارة مكتبة الوسائط بالكامل',
  'appointments.view': 'عرض المواعيد والتسجيلات',
  'appointments.create': 'إنشاء المواعيد والتسجيلات',
  'appointments.update': 'تعديل المواعيد والتسجيلات',
  'appointments.cancel': 'إلغاء المواعيد والتسجيلات',
  'appointments.delete': 'حذف المواعيد والتسجيلات',
  'appointments.assign': 'إسناد المواعيد والتسجيلات',
  'appointments.export': 'تصدير المواعيد والتسجيلات',
  'appointments.manage': 'إدارة المواعيد بالكامل',
  'leads.view': 'عرض العملاء المحتملين',
  'leads.create': 'إنشاء العملاء المحتملين',
  'leads.update': 'تعديل العملاء المحتملين',
  'leads.assign': 'إسناد العملاء المحتملين',
  'leads.export': 'تصدير العملاء المحتملين',
  'leads.delete': 'حذف العملاء المحتملين',
  'leads.manage': 'إدارة العملاء المحتملين بالكامل',
  'communications.view': 'عرض المحادثات',
  'communications.reply': 'إرسال والرد على المحادثات',
  'communications.assign': 'إسناد المحادثات',
  'communications.broadcast': 'إرسال البث الجماعي',
  'communications.templates.manage': 'إدارة قوالب الردود',
  'communications.archive': 'أرشفة المحادثات',
  'communications.delete': 'حذف المحادثات',
  'communications.manage': 'إدارة التواصل بالكامل',
  'campaigns.view': 'عرض الحملات',
  'campaigns.create': 'إنشاء الحملات',
  'campaigns.update': 'تعديل الحملات',
  'campaigns.delete': 'حذف الحملات',
  'campaigns.publish': 'نشر الحملات',
  'campaigns.archive': 'أرشفة الحملات',
  'campaigns.export': 'تصدير الحملات',
  'campaigns.manage': 'إدارة الحملات بالكامل',
  'reports.view': 'عرض التقارير',
  'reports.export': 'تصدير التقارير',
  'tasks.view': 'عرض المهام',
  'tasks.create': 'إنشاء المهام',
  'tasks.update': 'تعديل المهام',
  'tasks.assign': 'إسناد المهام',
  'tasks.complete': 'إكمال المهام',
  'tasks.delete': 'حذف المهام',
  'tasks.manage': 'إدارة المهام بالكامل',
  'notifications.view': 'عرض إعدادات الإشعارات',
  'notifications.send': 'إرسال إشعارات يدوية',
  'notifications.settings.manage': 'إدارة إعدادات الإشعارات التفصيلية',
  'notifications.manage': 'إدارة إعدادات الإشعارات',
  'settings.view': 'عرض إعدادات النظام',
  'settings.manage': 'إدارة إعدادات النظام',
  'integrations.view': 'عرض التكاملات',
  'integrations.connect': 'ربط التكاملات',
  'integrations.disconnect': 'فصل التكاملات',
  'integrations.credentials.manage': 'إدارة بيانات اعتماد التكاملات',
  'integrations.manage': 'إدارة التكاملات',
  'privacy.view': 'عرض إعدادات وسجل الخصوصية',
  'privacy.manage': 'إدارة إعدادات الخصوصية والموافقات',
  'privacy.export': 'تصدير سجلات الخصوصية',
  'operations.view': 'عرض العمليات والنسخ',
  'operations.import': 'استيراد البيانات',
  'operations.export': 'تصدير البيانات والنسخ',
  'operations.backup': 'إنشاء نسخة احتياطية',
  'operations.restore': 'استعادة نسخة احتياطية',
  'operations.manage': 'إدارة النسخ والعمليات',
  'audit.view': 'عرض سجل التدقيق',
  'audit.export': 'تصدير سجل التدقيق',
};

export const DEFAULT_ROLE_DEFINITIONS: Record<
  RoleBaseKey,
  { name: string; description: string; permissions: RolePermission[] }
> = {
  admin: {
    name: 'مسؤول النظام',
    description: 'إدارة شاملة للنظام والمستخدمين.',
    permissions: [...ROLE_PERMISSIONS],
  },
  manager: {
    name: 'مدير',
    description: 'إدارة التشغيل والمحتوى والتقارير دون إعدادات النظام الحساسة.',
    permissions: [
      'dashboard.view',
      'users.view',
      'content.view',
      'content.create',
      'content.update',
      'content.review',
      'content.manage',
      'content.publish',
      'media.view',
      'media.upload',
      'media.delete',
      'media.manage',
      'appointments.view',
      'appointments.create',
      'appointments.update',
      'appointments.cancel',
      'appointments.manage',
      'leads.view',
      'leads.create',
      'leads.update',
      'leads.assign',
      'leads.manage',
      'communications.view',
      'communications.reply',
      'communications.assign',
      'communications.broadcast',
      'communications.templates.manage',
      'communications.manage',
      'campaigns.view',
      'campaigns.create',
      'campaigns.update',
      'campaigns.delete',
      'campaigns.manage',
      'reports.view',
      'reports.export',
      'notifications.view',
    ],
  },
  staff: {
    name: 'موظف',
    description: 'تنفيذ العمليات اليومية المصرح بها.',
    permissions: [
      'dashboard.view',
      'content.view',
      'media.view',
      'appointments.view',
      'appointments.create',
      'appointments.update',
      'appointments.manage',
      'leads.view',
      'leads.create',
      'leads.update',
      'leads.manage',
      'communications.view',
      'communications.reply',
      'communications.manage',
    ],
  },
  team_leader: {
    name: 'قائد فريق',
    description: 'إدارة عمل الفريق والمحتوى والحملات ضمن نطاقه.',
    permissions: [
      'dashboard.view',
      'users.view',
      'content.view',
      'content.create',
      'content.update',
      'content.review',
      'content.manage',
      'media.view',
      'media.upload',
      'media.manage',
      'leads.view',
      'leads.create',
      'leads.update',
      'leads.assign',
      'leads.manage',
      'communications.view',
      'communications.reply',
      'communications.assign',
      'communications.templates.manage',
      'communications.manage',
      'campaigns.view',
      'campaigns.create',
      'campaigns.update',
      'campaigns.manage',
      'reports.view',
    ],
  },
  viewer: {
    name: 'مشاهد',
    description: 'عرض المعلومات المصرح بها فقط.',
    permissions: ['dashboard.view', 'content.view', 'media.view', 'reports.view'],
  },
  user: {
    name: 'مستخدم',
    description: 'وصول محدود إلى المهام والتنبيهات المسندة.',
    permissions: ['dashboard.view'],
  },
};
