export const ROLE_BASE_KEYS = [
  'admin',
  'manager',
  'staff',
  'team_leader',
  'viewer',
  'user',
] as const;
export type RoleBaseKey = (typeof ROLE_BASE_KEYS)[number];

export const ROLE_PERMISSIONS = [
  'dashboard.view',
  'users.view',
  'users.create',
  'users.update',
  'users.deactivate',
  'users.manage',
  'roles.manage',
  'content.view',
  'content.create',
  'content.update',
  'content.delete',
  'content.review',
  'content.manage',
  'content.publish',
  'media.view',
  'media.upload',
  'media.delete',
  'media.manage',
  'appointments.view',
  'appointments.create',
  'appointments.update',
  'appointments.cancel',
  'appointments.manage',
  'leads.view',
  'leads.create',
  'leads.update',
  'leads.assign',
  'leads.delete',
  'leads.manage',
  'communications.view',
  'communications.reply',
  'communications.assign',
  'communications.broadcast',
  'communications.templates.manage',
  'communications.manage',
  'campaigns.view',
  'campaigns.create',
  'campaigns.update',
  'campaigns.delete',
  'campaigns.manage',
  'reports.view',
  'reports.export',
  'notifications.view',
  'notifications.manage',
  'settings.view',
  'settings.manage',
  'integrations.manage',
  'operations.manage',
  'audit.view',
] as const;

export type RolePermission = (typeof ROLE_PERMISSIONS)[number];

export const ROLE_PERMISSION_GROUPS = [
  {
    key: 'dashboard',
    label: 'لوحة التحكم والتقارير',
    permissions: ['dashboard.view', 'reports.view', 'reports.export'],
  },
  {
    key: 'users',
    label: 'المستخدمون والأدوار',
    permissions: [
      'users.view',
      'users.create',
      'users.update',
      'users.deactivate',
      'users.manage',
      'roles.manage',
    ],
  },
  {
    key: 'content',
    label: 'المحتوى والنشر',
    permissions: [
      'content.view',
      'content.create',
      'content.update',
      'content.delete',
      'content.review',
      'content.manage',
      'content.publish',
    ],
  },
  {
    key: 'media',
    label: 'الوسائط',
    permissions: ['media.view', 'media.upload', 'media.delete', 'media.manage'],
  },
  {
    key: 'appointments',
    label: 'المواعيد والتسجيلات',
    permissions: [
      'appointments.view',
      'appointments.create',
      'appointments.update',
      'appointments.cancel',
      'appointments.manage',
    ],
  },
  {
    key: 'leads',
    label: 'العملاء المحتملون',
    permissions: [
      'leads.view',
      'leads.create',
      'leads.update',
      'leads.assign',
      'leads.delete',
      'leads.manage',
    ],
  },
  {
    key: 'communications',
    label: 'التواصل والصندوق الموحد',
    permissions: [
      'communications.view',
      'communications.reply',
      'communications.assign',
      'communications.broadcast',
      'communications.templates.manage',
      'communications.manage',
    ],
  },
  {
    key: 'campaigns',
    label: 'الحملات التسويقية',
    permissions: [
      'campaigns.view',
      'campaigns.create',
      'campaigns.update',
      'campaigns.delete',
      'campaigns.manage',
    ],
  },
  {
    key: 'governance',
    label: 'الحوكمة والإعدادات',
    permissions: [
      'notifications.view',
      'notifications.manage',
      'settings.view',
      'settings.manage',
      'integrations.manage',
      'operations.manage',
      'audit.view',
    ],
  },
] as const satisfies ReadonlyArray<{
  key: string;
  label: string;
  permissions: readonly RolePermission[];
}>;

export const ROLE_PERMISSION_LABELS: Record<RolePermission, string> = {
  'dashboard.view': 'عرض لوحة التحكم',
  'users.view': 'عرض المستخدمين',
  'users.create': 'إضافة مستخدمين',
  'users.update': 'تعديل المستخدمين',
  'users.deactivate': 'تعطيل المستخدمين',
  'users.manage': 'إدارة المستخدمين بالكامل',
  'roles.manage': 'إدارة الأدوار والصلاحيات',
  'content.view': 'عرض المحتوى',
  'content.create': 'إنشاء المحتوى',
  'content.update': 'تعديل المحتوى',
  'content.delete': 'حذف المحتوى',
  'content.review': 'مراجعة المحتوى',
  'content.manage': 'إدارة المحتوى بالكامل',
  'content.publish': 'نشر المحتوى',
  'media.view': 'عرض مكتبة الوسائط',
  'media.upload': 'رفع الوسائط',
  'media.delete': 'حذف الوسائط',
  'media.manage': 'إدارة مكتبة الوسائط بالكامل',
  'appointments.view': 'عرض المواعيد والتسجيلات',
  'appointments.create': 'إنشاء المواعيد والتسجيلات',
  'appointments.update': 'تعديل المواعيد والتسجيلات',
  'appointments.cancel': 'إلغاء المواعيد والتسجيلات',
  'appointments.manage': 'إدارة المواعيد بالكامل',
  'leads.view': 'عرض العملاء المحتملين',
  'leads.create': 'إنشاء العملاء المحتملين',
  'leads.update': 'تعديل العملاء المحتملين',
  'leads.assign': 'إسناد العملاء المحتملين',
  'leads.delete': 'حذف العملاء المحتملين',
  'leads.manage': 'إدارة العملاء المحتملين بالكامل',
  'communications.view': 'عرض المحادثات',
  'communications.reply': 'إرسال والرد على المحادثات',
  'communications.assign': 'إسناد المحادثات',
  'communications.broadcast': 'إرسال البث الجماعي',
  'communications.templates.manage': 'إدارة قوالب الردود',
  'communications.manage': 'إدارة التواصل بالكامل',
  'campaigns.view': 'عرض الحملات',
  'campaigns.create': 'إنشاء الحملات',
  'campaigns.update': 'تعديل الحملات',
  'campaigns.delete': 'حذف الحملات',
  'campaigns.manage': 'إدارة الحملات بالكامل',
  'reports.view': 'عرض التقارير',
  'reports.export': 'تصدير التقارير',
  'notifications.view': 'عرض إعدادات الإشعارات',
  'notifications.manage': 'إدارة إعدادات الإشعارات',
  'settings.view': 'عرض إعدادات النظام',
  'settings.manage': 'إدارة إعدادات النظام',
  'integrations.manage': 'إدارة التكاملات',
  'operations.manage': 'إدارة النسخ والعمليات',
  'audit.view': 'عرض سجل التدقيق',
};

export const DEFAULT_ROLE_DEFINITIONS: Record<
  RoleBaseKey,
  { name: string; description: string; permissions: RolePermission[] }
> = {
  admin: {
    name: 'مسؤول النظام',
    description: 'إدارة شاملة للنظام والمستخدمين.',
    permissions: [...ROLE_PERMISSIONS],
  },
  manager: {
    name: 'مدير',
    description: 'إدارة التشغيل والمحتوى والتقارير دون إعدادات النظام الحساسة.',
    permissions: [
      'dashboard.view',
      'users.view',
      'content.view',
      'content.create',
      'content.update',
      'content.review',
      'content.manage',
      'content.publish',
      'media.view',
      'media.upload',
      'media.delete',
      'media.manage',
      'appointments.view',
      'appointments.create',
      'appointments.update',
      'appointments.cancel',
      'appointments.manage',
      'leads.view',
      'leads.create',
      'leads.update',
      'leads.assign',
      'leads.manage',
      'communications.view',
      'communications.reply',
      'communications.assign',
      'communications.broadcast',
      'communications.templates.manage',
      'communications.manage',
      'campaigns.view',
      'campaigns.create',
      'campaigns.update',
      'campaigns.delete',
      'campaigns.manage',
      'reports.view',
      'reports.export',
      'notifications.view',
    ],
  },
  staff: {
    name: 'موظف',
    description: 'تنفيذ العمليات اليومية المصرح بها.',
    permissions: [
      'dashboard.view',
      'content.view',
      'media.view',
      'appointments.view',
      'appointments.create',
      'appointments.update',
      'appointments.manage',
      'leads.view',
      'leads.create',
      'leads.update',
      'leads.manage',
      'communications.view',
      'communications.reply',
      'communications.manage',
    ],
  },
  team_leader: {
    name: 'قائد فريق',
    description: 'إدارة عمل الفريق والمحتوى والحملات ضمن نطاقه.',
    permissions: [
      'dashboard.view',
      'users.view',
      'content.view',
      'content.create',
      'content.update',
      'content.review',
      'content.manage',
      'media.view',
      'media.upload',
      'media.manage',
      'leads.view',
      'leads.create',
      'leads.update',
      'leads.assign',
      'leads.manage',
      'communications.view',
      'communications.reply',
      'communications.assign',
      'communications.templates.manage',
      'communications.manage',
      'campaigns.view',
      'campaigns.create',
      'campaigns.update',
      'campaigns.manage',
      'reports.view',
    ],
  },
  viewer: {
    name: 'مشاهد',
    description: 'عرض المعلومات المصرح بها فقط.',
    permissions: ['dashboard.view', 'content.view', 'media.view', 'reports.view'],
  },
  user: {
    name: 'مستخدم',
    description: 'وصول محدود إلى المهام والتنبيهات المسندة.',
    permissions: ['dashboard.view'],
  },
};
