export const ROLE_BASE_KEYS = [
  'admin',
  'manager',
  'staff',
  'team_leader',
  'viewer',
  'user',
] as const;
export type RoleBaseKey = (typeof ROLE_BASE_KEYS)[number];

export const ROLE_PERMISSIONS = [
  'dashboard.view',
  'dashboard.customize',
  'users.view',
  'users.create',
  'users.update',
  'users.deactivate',
  'users.delete',
  'users.assign_role',
  'users.manage',
  'users.access_requests.view',
  'users.access_requests.decide',
  'roles.manage',
  'roles.view',
  'roles.create',
  'roles.update',
  'roles.delete',
  'content.view',
  'content.create',
  'content.update',
  'content.delete',
  'content.restore',
  'content.review',
  'content.manage',
  'content.publish',
  'content.schedule',
  'content.duplicate',
  'content.export',
  'content.import',
  'content.seo.manage',
  'content.translations.manage',
  'content.preview',
  'media.view',
  'media.upload',
  'media.organize',
  'media.download',
  'media.rename',
  'media.delete',
  'media.manage',
  'media.replace',
  'media.metadata.update',
  'media.restore',
  'appointments.view',
  'appointments.create',
  'appointments.update',
  'appointments.cancel',
  'appointments.delete',
  'appointments.assign',
  'appointments.export',
  'appointments.manage',
  'appointments.reschedule',
  'appointments.check_in',
  'appointments.status.update',
  'appointments.import',
  'leads.view',
  'leads.create',
  'leads.update',
  'leads.assign',
  'leads.export',
  'leads.delete',
  'leads.manage',
  'leads.status.update',
  'leads.convert',
  'leads.merge',
  'leads.import',
  'communications.view',
  'communications.reply',
  'communications.assign',
  'communications.broadcast',
  'communications.templates.manage',
  'communications.archive',
  'communications.delete',
  'communications.manage',
  'communications.mark_read',
  'communications.internal_note',
  'communications.comment.moderate',
  'communications.private_reply',
  'communications.security.view',
  'communications.security.manage',
  'communications.consents.view',
  'communications.consents.manage',
  'communications.automation.view',
  'communications.automation.manage',
  'communications.testing.view',
  'communications.testing.send',
  'campaigns.view',
  'campaigns.create',
  'campaigns.update',
  'campaigns.delete',
  'campaigns.publish',
  'campaigns.archive',
  'campaigns.export',
  'campaigns.manage',
  'campaigns.duplicate',
  'campaigns.budget.manage',
  'campaigns.metrics.manage',
  'campaigns.links.manage',
  'reports.view',
  'reports.export',
  'reports.schedule',
  'reports.share',
  'tasks.view',
  'tasks.create',
  'tasks.update',
  'tasks.assign',
  'tasks.complete',
  'tasks.delete',
  'tasks.manage',
  'tasks.comments.manage',
  'tasks.attachments.manage',
  'notifications.view',
  'notifications.send',
  'notifications.settings.manage',
  'notifications.manage',
  'notifications.mark_read',
  'notifications.templates.manage',
  'notifications.preferences.manage',
  'settings.view',
  'settings.manage',
  'settings.branding.manage',
  'settings.tracking.manage',
  'settings.license.manage',
  'integrations.view',
  'integrations.connect',
  'integrations.disconnect',
  'integrations.credentials.manage',
  'integrations.manage',
  'integrations.assets.manage',
  'integrations.webhooks.manage',
  'integrations.sync.manage',
  'integrations.logs.view',
  'privacy.view',
  'privacy.manage',
  'privacy.export',
  'privacy.policy.publish',
  'privacy.consents.manage',
  'operations.view',
  'operations.import',
  'operations.export',
  'operations.backup',
  'operations.restore',
  'operations.manage',
  'operations.queue.manage',
  'operations.scheduler.manage',
  'operations.retention.manage',
  'operations.purge',
  'audit.view',
  'audit.export',
  'catalog.view',
  'catalog.create',
  'catalog.update',
  'catalog.publish',
  'catalog.archive',
  'catalog.delete',
  'catalog.export',
  'catalog.manage',
  'registrations.view',
  'registrations.update',
  'registrations.assign',
  'registrations.export',
  'registrations.delete',
  'registrations.manage',
  'customers.view',
  'customers.export',
  'patients.view',
  'patients.records.manage',
  'patients.results.manage',
  'patients.results.view',
  'patients.results.create',
  'patients.results.status.update',
] as const;

export type RolePermission = (typeof ROLE_PERMISSIONS)[number];

export const ROLE_PERMISSION_GROUPS = [
  {
    key: 'dashboard',
    label: 'نظرة عامة والتقارير',
    permissions: ['dashboard.view', 'dashboard.customize', 'reports.view', 'reports.export'],
  },
  {
    key: 'users',
    label: 'المستخدمون والوصول',
    permissions: [
      'users.view',
      'users.create',
      'users.update',
      'users.deactivate',
      'users.delete',
      'users.assign_role',
      'users.manage',
      'users.access_requests.view',
      'users.access_requests.decide',
      'roles.view',
      'roles.manage',
      'roles.create',
      'roles.update',
      'roles.delete',
    ],
  },
  {
    key: 'catalog',
    label: 'الكتالوج الطبي والعروض',
    permissions: [
      'catalog.view',
      'catalog.create',
      'catalog.update',
      'catalog.publish',
      'catalog.archive',
      'catalog.delete',
      'catalog.export',
      'catalog.manage',
    ],
  },
  {
    key: 'registrations',
    label: 'التسجيلات والنماذج',
    permissions: [
      'registrations.view',
      'registrations.update',
      'registrations.assign',
      'registrations.export',
      'registrations.delete',
      'registrations.manage',
    ],
  },
  {
    key: 'customers',
    label: 'ملفات العملاء الموحدة',
    permissions: ['customers.view', 'customers.export'],
  },
  {
    key: 'patients',
    label: 'ملفات المرضى والنتائج',
    permissions: [
      'patients.view',
      'patients.records.manage',
      'patients.results.view',
      'patients.results.create',
      'patients.results.status.update',
      'patients.results.manage',
    ],
  },
  {
    key: 'content',
    label: 'المحتوى والموقع',
    permissions: [
      'content.view',
      'content.create',
      'content.update',
      'content.delete',
      'content.restore',
      'content.review',
      'content.manage',
      'content.publish',
      'content.schedule',
      'content.duplicate',
      'content.export',
      'content.import',
      'content.seo.manage',
      'content.translations.manage',
      'content.preview',
    ],
  },
  {
    key: 'media',
    label: 'الوسائط والملفات',
    permissions: [
      'media.view',
      'media.upload',
      'media.organize',
      'media.download',
      'media.rename',
      'media.delete',
      'media.manage',
      'media.replace',
      'media.metadata.update',
      'media.restore',
    ],
  },
  {
    key: 'appointments',
    label: 'المواعيد والحجوزات',
    permissions: [
      'appointments.view',
      'appointments.create',
      'appointments.update',
      'appointments.cancel',
      'appointments.delete',
      'appointments.assign',
      'appointments.export',
      'appointments.manage',
      'appointments.reschedule',
      'appointments.check_in',
      'appointments.status.update',
      'appointments.import',
    ],
  },
  {
    key: 'leads',
    label: 'علاقات العملاء المحتملين',
    permissions: [
      'leads.view',
      'leads.create',
      'leads.update',
      'leads.assign',
      'leads.export',
      'leads.delete',
      'leads.manage',
      'leads.status.update',
      'leads.convert',
      'leads.merge',
      'leads.import',
    ],
  },
  {
    key: 'communications',
    label: 'التواصل وWhatsApp والصندوق الموحد',
    permissions: [
      'communications.view',
      'communications.reply',
      'communications.assign',
      'communications.broadcast',
      'communications.templates.manage',
      'communications.archive',
      'communications.delete',
      'communications.manage',
      'communications.mark_read',
      'communications.internal_note',
      'communications.comment.moderate',
      'communications.private_reply',
      'communications.security.view',
      'communications.security.manage',
      'communications.consents.view',
      'communications.consents.manage',
      'communications.automation.view',
      'communications.automation.manage',
      'communications.testing.view',
      'communications.testing.send',
    ],
  },
  {
    key: 'campaigns',
    label: 'التسويق والحملات',
    permissions: [
      'campaigns.view',
      'campaigns.create',
      'campaigns.update',
      'campaigns.delete',
      'campaigns.publish',
      'campaigns.archive',
      'campaigns.export',
      'campaigns.manage',
      'campaigns.duplicate',
      'campaigns.budget.manage',
      'campaigns.metrics.manage',
      'campaigns.links.manage',
    ],
  },
  {
    key: 'tasks',
    label: 'المهام والمتابعة والفرق',
    permissions: [
      'tasks.view',
      'tasks.create',
      'tasks.update',
      'tasks.assign',
      'tasks.complete',
      'tasks.delete',
      'tasks.manage',
      'tasks.comments.manage',
      'tasks.attachments.manage',
    ],
  },
  {
    key: 'notifications',
    label: 'الإشعارات',
    permissions: [
      'notifications.view',
      'notifications.send',
      'notifications.settings.manage',
      'notifications.manage',
      'notifications.mark_read',
      'notifications.templates.manage',
      'notifications.preferences.manage',
    ],
  },
  {
    key: 'integrations',
    label: 'الربط والتكاملات',
    permissions: [
      'integrations.view',
      'integrations.connect',
      'integrations.disconnect',
      'integrations.credentials.manage',
      'integrations.manage',
      'integrations.assets.manage',
      'integrations.webhooks.manage',
      'integrations.sync.manage',
      'integrations.logs.view',
    ],
  },
  {
    key: 'governance',
    label: 'الإعدادات والحوكمة والعمليات',
    permissions: [
      'settings.view',
      'settings.manage',
      'settings.branding.manage',
      'settings.tracking.manage',
      'settings.license.manage',
      'privacy.view',
      'privacy.manage',
      'privacy.export',
      'privacy.policy.publish',
      'privacy.consents.manage',
      'operations.view',
      'operations.import',
      'operations.export',
      'operations.backup',
      'operations.restore',
      'operations.manage',
      'operations.queue.manage',
      'operations.scheduler.manage',
      'operations.retention.manage',
      'operations.purge',
      'audit.view',
      'audit.export',
      'reports.schedule',
      'reports.share',
    ],
  },
] as const satisfies ReadonlyArray<{
  key: string;
  label: string;
  permissions: readonly RolePermission[];
}>;

export const ROLE_PERMISSION_LABELS: Record<RolePermission, string> = {
  'dashboard.view': 'عرض لوحة التحكم',
  'dashboard.customize': 'تخصيص لوحة التحكم',
  'users.view': 'عرض المستخدمين',
  'users.create': 'إضافة مستخدمين',
  'users.update': 'تعديل المستخدمين',
  'users.deactivate': 'تعطيل المستخدمين',
  'users.delete': 'حذف المستخدمين',
  'users.assign_role': 'تعيين أدوار المستخدمين',
  'users.manage': 'إدارة المستخدمين بالكامل',
  'users.access_requests.view': 'عرض طلبات الوصول',
  'users.access_requests.decide': 'قبول ورفض طلبات الوصول',
  'roles.manage': 'إدارة الأدوار والصلاحيات',
  'roles.view': 'عرض الأدوار والصلاحيات',
  'roles.create': 'إنشاء أدوار جديدة',
  'roles.update': 'تعديل الأدوار والصلاحيات',
  'roles.delete': 'حذف الأدوار المخصصة',
  'content.view': 'عرض المحتوى',
  'content.create': 'إنشاء المحتوى',
  'content.update': 'تعديل المحتوى',
  'content.delete': 'حذف المحتوى',
  'content.restore': 'استعادة المحتوى',
  'content.review': 'مراجعة المحتوى',
  'content.manage': 'إدارة المحتوى بالكامل',
  'content.publish': 'نشر المحتوى',
  'content.schedule': 'جدولة نشر المحتوى',
  'content.duplicate': 'نسخ المحتوى والأقسام',
  'content.export': 'تصدير حزم المحتوى',
  'content.import': 'استيراد حزم المحتوى',
  'content.seo.manage': 'إدارة إعدادات SEO',
  'content.translations.manage': 'إدارة ترجمات المحتوى',
  'content.preview': 'معاينة المحتوى قبل النشر',
  'media.view': 'عرض مكتبة الوسائط',
  'media.upload': 'رفع الوسائط',
  'media.organize': 'تنظيم المجلدات والوسائط',
  'media.download': 'تنزيل الوسائط',
  'media.rename': 'إعادة تسمية الوسائط',
  'media.delete': 'حذف الوسائط',
  'media.manage': 'إدارة مكتبة الوسائط بالكامل',
  'media.replace': 'استبدال ملفات الوسائط',
  'media.metadata.update': 'تعديل بيانات الوسائط الوصفية',
  'media.restore': 'استعادة الوسائط المحذوفة',
  'appointments.view': 'عرض المواعيد والتسجيلات',
  'appointments.create': 'إنشاء المواعيد والتسجيلات',
  'appointments.update': 'تعديل المواعيد والتسجيلات',
  'appointments.cancel': 'إلغاء المواعيد والتسجيلات',
  'appointments.delete': 'حذف المواعيد والتسجيلات',
  'appointments.assign': 'إسناد المواعيد والتسجيلات',
  'appointments.export': 'تصدير المواعيد والتسجيلات',
  'appointments.manage': 'إدارة المواعيد بالكامل',
  'appointments.reschedule': 'إعادة جدولة المواعيد',
  'appointments.check_in': 'تأكيد حضور المواعيد',
  'appointments.status.update': 'تغيير حالات المواعيد',
  'appointments.import': 'استيراد المواعيد والتسجيلات',
  'leads.view': 'عرض العملاء المحتملين',
  'leads.create': 'إنشاء العملاء المحتملين',
  'leads.update': 'تعديل العملاء المحتملين',
  'leads.assign': 'إسناد العملاء المحتملين',
  'leads.export': 'تصدير العملاء المحتملين',
  'leads.delete': 'حذف العملاء المحتملين',
  'leads.manage': 'إدارة العملاء المحتملين بالكامل',
  'leads.status.update': 'تغيير حالة العميل المحتمل',
  'leads.convert': 'تحويل العميل المحتمل',
  'leads.merge': 'دمج العملاء المحتملين المكررين',
  'leads.import': 'استيراد العملاء المحتملين',
  'communications.view': 'عرض المحادثات',
  'communications.reply': 'إرسال والرد على المحادثات',
  'communications.assign': 'إسناد المحادثات',
  'communications.broadcast': 'إرسال البث الجماعي',
  'communications.templates.manage': 'إدارة قوالب الردود',
  'communications.archive': 'أرشفة المحادثات',
  'communications.delete': 'حذف المحادثات',
  'communications.manage': 'إدارة التواصل بالكامل',
  'communications.mark_read': 'تغيير حالة قراءة المحادثات',
  'communications.internal_note': 'إضافة ملاحظات داخلية للمحادثات',
  'communications.comment.moderate': 'إدارة تعليقات المنصات',
  'communications.private_reply': 'إرسال ردود خاصة من التعليقات',
  'communications.security.view': 'عرض أمان WhatsApp والامتثال',
  'communications.security.manage': 'إدارة أمان WhatsApp والامتثال',
  'communications.consents.view': 'عرض موافقات واشتراكات WhatsApp',
  'communications.consents.manage': 'إدارة موافقات واشتراكات WhatsApp',
  'communications.automation.view': 'عرض قواعد الرد الآلي في WhatsApp',
  'communications.automation.manage': 'إدارة قواعد الرد الآلي في WhatsApp',
  'communications.testing.view': 'عرض أدوات اختبار WhatsApp',
  'communications.testing.send': 'إرسال رسائل اختبار WhatsApp',
  'campaigns.view': 'عرض الحملات',
  'campaigns.create': 'إنشاء الحملات',
  'campaigns.update': 'تعديل الحملات',
  'campaigns.delete': 'حذف الحملات',
  'campaigns.publish': 'نشر الحملات',
  'campaigns.archive': 'أرشفة الحملات',
  'campaigns.export': 'تصدير الحملات',
  'campaigns.manage': 'إدارة الحملات بالكامل',
  'campaigns.duplicate': 'نسخ الحملات',
  'campaigns.budget.manage': 'إدارة ميزانيات الحملات',
  'campaigns.metrics.manage': 'إدارة مقاييس الحملات',
  'campaigns.links.manage': 'ربط العروض والمخيمات والأطباء بالحملات',
  'reports.view': 'عرض التقارير',
  'reports.export': 'تصدير التقارير',
  'reports.schedule': 'جدولة التقارير',
  'reports.share': 'مشاركة التقارير',
  'tasks.view': 'عرض المهام',
  'tasks.create': 'إنشاء المهام',
  'tasks.update': 'تعديل المهام',
  'tasks.assign': 'إسناد المهام',
  'tasks.complete': 'إكمال المهام',
  'tasks.delete': 'حذف المهام',
  'tasks.manage': 'إدارة المهام بالكامل',
  'tasks.comments.manage': 'إدارة تعليقات المهام',
  'tasks.attachments.manage': 'إدارة مرفقات المهام',
  'notifications.view': 'عرض إعدادات الإشعارات',
  'notifications.send': 'إرسال إشعارات يدوية',
  'notifications.settings.manage': 'إدارة إعدادات الإشعارات التفصيلية',
  'notifications.manage': 'إدارة إعدادات الإشعارات',
  'notifications.mark_read': 'تغيير حالة قراءة الإشعارات',
  'notifications.templates.manage': 'إدارة قوالب الإشعارات',
  'notifications.preferences.manage': 'إدارة تفضيلات إشعارات المستخدمين',
  'settings.view': 'عرض إعدادات النظام',
  'settings.manage': 'إدارة إعدادات النظام',
  'settings.branding.manage': 'إدارة هوية النظام ومظهره',
  'settings.tracking.manage': 'إدارة إعدادات التتبع والتحليلات',
  'settings.license.manage': 'إدارة ترخيص النظام وطلباته',
  'integrations.view': 'عرض التكاملات',
  'integrations.connect': 'ربط التكاملات',
  'integrations.disconnect': 'فصل التكاملات',
  'integrations.credentials.manage': 'إدارة بيانات اعتماد التكاملات',
  'integrations.manage': 'إدارة التكاملات',
  'integrations.assets.manage': 'اختيار أصول وحسابات التكاملات',
  'integrations.webhooks.manage': 'إدارة Webhooks التكاملات',
  'integrations.sync.manage': 'تشغيل مزامنة التكاملات',
  'integrations.logs.view': 'عرض سجلات التكاملات',
  'privacy.view': 'عرض إعدادات وسجل الخصوصية',
  'privacy.manage': 'إدارة إعدادات الخصوصية والموافقات',
  'privacy.export': 'تصدير سجلات الخصوصية',
  'privacy.policy.publish': 'نشر تحديثات سياسة الخصوصية',
  'privacy.consents.manage': 'إدارة موافقات الخصوصية',
  'operations.view': 'عرض العمليات والنسخ',
  'operations.import': 'استيراد البيانات',
  'operations.export': 'تصدير البيانات والنسخ',
  'operations.backup': 'إنشاء نسخة احتياطية',
  'operations.restore': 'استعادة نسخة احتياطية',
  'operations.manage': 'إدارة النسخ والعمليات',
  'operations.queue.manage': 'إدارة قوائم العمليات والطوابير',
  'operations.scheduler.manage': 'إدارة المهام المجدولة التشغيلية',
  'operations.retention.manage': 'إدارة سياسات الاحتفاظ',
  'operations.purge': 'تنفيذ الحذف النهائي للبيانات',
  'audit.view': 'عرض سجل التدقيق',
  'audit.export': 'تصدير سجل التدقيق',
  'catalog.view': 'عرض الأطباء والعروض والمخيمات',
  'catalog.create': 'إنشاء عناصر الكتالوج',
  'catalog.update': 'تعديل عناصر الكتالوج',
  'catalog.publish': 'نشر عناصر الكتالوج',
  'catalog.archive': 'أرشفة عناصر الكتالوج',
  'catalog.delete': 'حذف عناصر الكتالوج',
  'catalog.export': 'تصدير بيانات الكتالوج',
  'catalog.manage': 'إدارة الكتالوج بالكامل',
  'registrations.view': 'عرض التسجيلات والنماذج',
  'registrations.update': 'تعديل التسجيلات والنماذج',
  'registrations.assign': 'إسناد التسجيلات للموظفين',
  'registrations.export': 'تصدير التسجيلات والنماذج',
  'registrations.delete': 'حذف التسجيلات والنماذج',
  'registrations.manage': 'إدارة التسجيلات بالكامل',
  'customers.view': 'عرض ملفات العملاء الموحدة',
  'customers.export': 'تصدير ملفات العملاء',
  'patients.view': 'عرض ملفات المرضى',
  'patients.records.manage': 'إدارة ملفات المرضى',
  'patients.results.manage': 'إدارة نتائج المرضى',
  'patients.results.view': 'عرض نتائج المرضى',
  'patients.results.create': 'إضافة نتائج المرضى',
  'patients.results.status.update': 'تحديث حالة نتائج المرضى',
};

export const DEFAULT_ROLE_DEFINITIONS: Record<
  RoleBaseKey,
  { name: string; description: string; permissions: RolePermission[] }
> = {
  admin: {
    name: 'مسؤول النظام',
    description: 'إدارة شاملة للنظام والمستخدمين.',
    permissions: [...ROLE_PERMISSIONS],
  },
  manager: {
    name: 'مدير',
    description: 'إدارة التشغيل والمحتوى والتقارير دون إعدادات النظام الحساسة.',
    permissions: [
      'dashboard.view',
      'users.view',
      'content.view',
      'content.create',
      'content.update',
      'content.review',
      'content.manage',
      'content.publish',
      'content.schedule',
      'media.view',
      'media.upload',
      'media.delete',
      'media.manage',
      'appointments.view',
      'appointments.create',
      'appointments.update',
      'appointments.cancel',
      'appointments.manage',
      'leads.view',
      'leads.create',
      'leads.update',
      'leads.assign',
      'leads.manage',
      'communications.view',
      'communications.reply',
      'communications.assign',
      'communications.broadcast',
      'communications.templates.manage',
      'communications.manage',
      'campaigns.view',
      'campaigns.create',
      'campaigns.update',
      'campaigns.delete',
      'campaigns.manage',
      'reports.view',
      'reports.export',
      'notifications.view',
      'registrations.view',
    ],
  },
  staff: {
    name: 'موظف',
    description: 'تنفيذ العمليات اليومية المصرح بها.',
    permissions: [
      'dashboard.view',
      'content.view',
      'content.create',
      'content.update',
      'media.view',
      'appointments.view',
      'appointments.create',
      'appointments.update',
      'appointments.manage',
      'leads.view',
      'leads.create',
      'leads.update',
      'leads.manage',
      'communications.view',
      'communications.reply',
      'communications.manage',
      'registrations.view',
    ],
  },
  team_leader: {
    name: 'قائد فريق',
    description: 'إدارة عمل الفريق والمحتوى والحملات ضمن نطاقه.',
    permissions: [
      'dashboard.view',
      'users.view',
      'content.view',
      'content.create',
      'content.update',
      'content.review',
      'content.manage',
      'media.view',
      'media.upload',
      'media.manage',
      'appointments.view',
      'leads.view',
      'leads.create',
      'leads.update',
      'leads.assign',
      'leads.manage',
      'communications.view',
      'communications.reply',
      'communications.assign',
      'communications.templates.manage',
      'communications.manage',
      'campaigns.view',
      'campaigns.create',
      'campaigns.update',
      'campaigns.manage',
      'reports.view',
      'registrations.view',
    ],
  },
  viewer: {
    name: 'مشاهد',
    description: 'عرض المعلومات المصرح بها فقط.',
    permissions: ['dashboard.view', 'media.view', 'reports.view'],
  },
  user: {
    name: 'مستخدم',
    description: 'وصول محدود إلى المهام والتنبيهات المسندة.',
    permissions: ['dashboard.view'],
  },
};
