#!/usr/bin/env tsx
/**
 * Generate License Key Tool
 * 
 * Generates digitally signed license keys using the private key.
 * Creates license files with Hardware ID binding, expiry dates, and feature flags.
 * 
 * Usage:
 *   pnpm license:generate <hardwareId> <expiryTimestamp> <features>
 *   pnpm license:generate <hardwareId> <expiryTimestamp> <features> --private-key <path>
 * 
 * Examples:
 *   pnpm license:generate "ABC123DEF456" 1735689600 "whatsapp,reports,patient_portal"
 *   pnpm license:generate "ABC123DEF456" 1735689600 "*" --private-key ./license-keys/private-key.pem
 * 
 * Security Notes:
 * - Requires the private key generated by generate-key-pair.ts
 * - Keep the private key secure and never distribute it
 * - License keys are digitally signed using RSA-2048
 * - Hardware ID binding prevents license copying
 */

import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * License payload interface
 */
interface LicensePayload {
  hid: string;           // Hardware ID
  exp: number;           // Expiry timestamp (Unix timestamp)
  feat: string[];        // Enabled features
  iat: number;           // Issued at timestamp
  ver: string;           // License version
}

/**
 * License key generation options
 */
interface LicenseOptions {
  hardwareId: string;
  expiryTimestamp: number;
  features: string[];
  privateKeyPath?: string;
  outputDir?: string;
  outputFile?: string;
}

/**
 * Generate a digitally signed license key
 * @param options - License generation options
 * @returns Base64 encoded license key
 */
function generateLicenseKey(options: LicenseOptions): string {
  const {
    hardwareId,
    expiryTimestamp,
    features,
    privateKeyPath = path.join(__dirname, '..', 'license-keys', 'private-key.pem'),
    outputDir = path.join(__dirname, '..', 'license-files'),
    outputFile,
  } = options;

  console.log('🔐 Generating License Key...');
  console.log('⚙️  License Details:');
  console.log(`   - Hardware ID: ${hardwareId}`);
  console.log(`   - Expiry Date: ${new Date(expiryTimestamp * 1000).toISOString()}`);
  console.log(`   - Features: ${features.join(', ')}`);
  console.log(`   - Private Key: ${privateKeyPath}`);
  console.log('');

  // Validate inputs
  if (!hardwareId || hardwareId.trim().length === 0) {
    throw new Error('Hardware ID is required');
  }

  if (!expiryTimestamp || expiryTimestamp <= Math.floor(Date.now() / 1000)) {
    throw new Error('Expiry timestamp must be in the future');
  }

  if (!features || features.length === 0) {
    throw new Error('At least one feature must be specified');
  }

  // Check if private key exists
  if (!fs.existsSync(privateKeyPath)) {
    throw new Error(`Private key not found at: ${privateKeyPath}`);
  }

  // Read private key
  const privateKey = fs.readFileSync(privateKeyPath, 'utf-8');
  console.log('✅ Private key loaded successfully');

  // Create license payload
  const payload: LicensePayload = {
    hid: hardwareId.toUpperCase().trim(),
    exp: expiryTimestamp,
    feat: features,
    iat: Math.floor(Date.now() / 1000),
    ver: '1.0',
  };

  console.log('📋 License Payload:', JSON.stringify(payload, null, 2));
  console.log('');

  // Sign the payload
  const payloadString = JSON.stringify(payload);
  const signature = crypto.sign('sha256', Buffer.from(payloadString), {
    key: privateKey,
    padding: crypto.constants.RSA_PKCS1_PSS_PADDING,
    saltLength: crypto.constants.RSA_PSS_SALTLEN_DIGEST,
  });

  // Create license object with signature
  const licenseObject = {
    payload,
    signature: signature.toString('base64'),
  };

  // Convert to base64 for distribution
  const licenseKey = Buffer.from(JSON.stringify(licenseObject)).toString('base64');

  console.log('✅ License key generated successfully');
  console.log('');

  // Save license file
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const outputFileName = outputFile || `license-${hardwareId}.json`;
  const outputFilePath = path.join(outputDir, outputFileName);

  const licenseFile = {
    key: licenseKey,
    hardwareId: payload.hid,
    expiryDate: new Date(payload.exp * 1000).toISOString(),
    features: payload.feat,
    issuedAt: new Date(payload.iat * 1000).toISOString(),
    version: payload.ver,
  };

  fs.writeFileSync(outputFilePath, JSON.stringify(licenseFile, null, 2));
  console.log('📄 License file saved:', outputFilePath);

  // Output the license key
  console.log('');
  console.log('🔑 LICENSE KEY:');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log(licenseKey);
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('');

  console.log('📋 License Information:');
  console.log('   - Hardware ID:', licenseFile.hardwareId);
  console.log('   - Expiry Date:', licenseFile.expiryDate);
  console.log('   - Features:', licenseFile.features.join(', '));
  console.log('   - Issued At:', licenseFile.issuedAt);
  console.log('   - Version:', licenseFile.version);
  console.log('');

  console.log('📋 Next Steps:');
  console.log('   1. Copy the license key and save it as license.json in the application directory');
  console.log('   2. Test license validation by running the application');
  console.log('   3. Ensure the Hardware ID matches the target machine');
  console.log('');

  return licenseKey;
}

/**
 * Main execution
 */
function main() {
  try {
    const args = process.argv.slice(2);

    if (args.length < 3) {
      console.error('❌ Missing required arguments');
      console.log('');
      console.log('Usage: pnpm license:generate <hardwareId> <expiryTimestamp> <features> [options]');
      console.log('');
      console.log('Arguments:');
      console.log('  hardwareId           Hardware ID of the target machine (e.g., ABC123DEF456)');
      console.log('  expiryTimestamp      Unix timestamp when license expires (e.g., 1735689600)');
      console.log('  features             Comma-separated list of features (e.g., whatsapp,reports,patient_portal)');
      console.log('');
      console.log('Options:');
      console.log('  --private-key <path>   Path to private key (default: ./license-keys/private-key.pem)');
      console.log('  --output-dir <dir>    Output directory for license file (default: ./license-files)');
      console.log('  --output-file <file>  License filename (default: license-<hardwareId>.json)');
      console.log('  --help                Show this help message');
      console.log('');
      console.log('Examples:');
      console.log('  pnpm license:generate "ABC123DEF456" 1735689600 "whatsapp,reports,patient_portal"');
      console.log('  pnpm license:generate "ABC123DEF456" 1735689600 "*" --output-file license-prod.json');
      console.log('  pnpm license:generate "ABC123DEF456" 1735689600 "whatsapp,reports" --private-key ./secure-keys/private-key.pem');
      console.log('');
      console.log('Calculate Expiry Timestamp:');
      console.log('  - 30 days: Math.floor(Date.now() / 1000) + (30 * 24 * 60 * 60)');
      console.log('  - 1 year: Math.floor(Date.now() / 1000) + (365 * 24 * 60 * 60)');
      console.log('');
      process.exit(1);
    }

    const hardwareId = args[0];
    const expiryTimestamp = parseInt(args[1], 10);
    const features = args[2].split(',').map(f => f.trim());

    const options: LicenseOptions = {
      hardwareId,
      expiryTimestamp,
      features,
    };

    // Parse optional arguments
    for (let i = 3; i < args.length; i++) {
      switch (args[i]) {
        case '--private-key':
          options.privateKeyPath = args[++i];
          break;
        case '--output-dir':
          options.outputDir = args[++i];
          break;
        case '--output-file':
          options.outputFile = args[++i];
          break;
        case '--help':
          console.log(`
Usage: pnpm license:generate <hardwareId> <expiryTimestamp> <features> [options]

Arguments:
  hardwareId           Hardware ID of the target machine (e.g., ABC123DEF456)
  expiryTimestamp      Unix timestamp when license expires (e.g., 1735689600)
  features             Comma-separated list of features (e.g., whatsapp,reports,patient_portal)

Options:
  --private-key <path>   Path to private key (default: ./license-keys/private-key.pem)
  --output-dir <dir>    Output directory for license file (default: ./license-files)
  --output-file <file>  License filename (default: license-<hardwareId>.json)
  --help                Show this help message

Examples:
  pnpm license:generate "ABC123DEF456" 1735689600 "whatsapp,reports,patient_portal"
  pnpm license:generate "ABC123DEF456" 1735689600 "*" --output-file license-prod.json
  pnpm license:generate "ABC123DEF456" 1735689600 "whatsapp,reports" --private-key ./secure-keys/private-key.pem

Calculate Expiry Timestamp:
  - 30 days: Math.floor(Date.now() / 1000) + (30 * 24 * 60 * 60)
  - 1 year: Math.floor(Date.now() / 1000) + (365 * 24 * 60 * 60)
          `);
          process.exit(0);
        default:
          console.error('❌ Unknown option:', args[i]);
          console.log('Use --help for usage information');
          process.exit(1);
      }
    }

    generateLicenseKey(options);
  } catch (error) {
    console.error('❌ Error generating license key:', error);
    process.exit(1);
  }
}

// Run the tool
main();